[package]
name = "charizhard-ota"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.8.0", features = ["attributes"] }
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.14.0"
tide = "0.16.0"
