name: Rust and Docker

on:
  push:
    branches: [ "master" , "minio" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check Cargo Audits
      run: |
        cargo install cargo-audit --locked || cargo install cargo-audit --force
        cargo audit
    - name: Build
      run: cargo build --verbose
