name: Rust and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check Cargo Audits
      run: |
        cargo install cargo-audit --locked || cargo install cargo-audit --force
        cargo audit
    - name: Build
      run: cargo build --verbose

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build Docker Image
      run: docker build -t funnyklown/docker-image-ota:latest .
    - name: Push Docker Image
      run: docker push funnyklown/docker-image-ota:latest
